### ISSUE TITLE
Unable to cast Python instance to C++ type

### ISSUE THREAD

**Issue by den7ba** [wallds/NoVmpy#13]
Try to analyze dumped kernel driver, protected VMP.
Command "Search" works, and correctly detects vmp-routines.
But command "LetsGo" failed, and write this: 

![image](https://user-images.githubusercontent.com/55707138/226465988-66b04e9f-87db-48f8-a660-a4c571e5ee61.png)

**Comment by den7ba** [comment]
![image](https://user-images.githubusercontent.com/55707138/226595879-a5390369-edd6-40f8-bc5c-8273a049b2c2.png)

Anyway... Strange but it works with dll from the same product

**Comment by wallds** [comment]
hi, den7ba. 
'ea' and 'vmstate.ip' looks strange, it's a dumped file? Maybe you need to modify the image base.
I haven't tested the driver dumped file, so there could be very many problems, can you share this sample?

**Comment by wallds** [comment]
ea: 0xfffff80298876299
vmstate.ip: fffff803986d49d7 (The correct value is fffff802986d49d7)

https://github.com/wallds/NoVmpy/blob/51f442af1c9063a7245b0e164e536e77b833695f/novmpy/handler.py#L1551

After I commented out this line of code, it worked fine.

**Comment by den7ba** [comment]
Yes, its works! Thanks for fast answers
