### ISSUE TITLE
Error on x86 Compile

### ISSUE THREAD

**Issue by smrbi** [wallds/NoVmpy#17]
I try all ways i know to compile x86 version
even i install python 3.8 x32 with adding "'-A', 'Win32'" to cmake command in setup.py

in this case i have this errors:
```
VTIL-Python/external/pybind11/include\pybind11/operators.h(94,11): error C2672: 'pybind11::class_<vtil::symbolic::directive::instance>::def': no matching ove
rloaded function found
```
```
/VTIL-Python/external/pybind11/include\pybind11/operators.h(154,1): error C2678: binary '-': no operator found which takes a left-hand operand of type 'const
L' (or there is no acceptable conversion)
```
```
VTIL-Python/external/pybind11/include\pybind11/operators.h(156,1): error C2678: binary '*': no operator found which takes a left-hand operand of type 'const
L' (or there is no acceptable conversion)
```
 

Please help me to compiling for  32bit target.
thank you.

**Comment by wallds** [comment]
hi, @smrbi 

This was actually fixed in https://github.com/wallds/VTIL-Python/commit/7f47d86fb1fcc7891a8cceaa868898efeb25a5f0, but I forgot to apply it to the `dev-x86` branch.

**Comment by smrbi** [comment]
Ok, thank you.
Compiled Success in with python-64bit but now IDA hangup on devirtualizing.
need to install python-32bit ?

**Comment by wallds** [comment]
Yes, you don't need to install Python-32bit. Since IDA version 7.0, both ida.exe and ida64.exe have become 64-bit applications.

**Comment by smrbi** [comment]
yes, i compiled dev-x86 with python-3.9.6-x64 and install capstone-4.0.2 but on devirtualizing, IDA hanged.

**Comment by smrbi** [comment]
Please check this target:
[](https://github.com/smrbi/public/blob/main/x32.vmp.exe.7z)
i compile dev-x86 + Fix11 but IDA with hang, and Handler list is empty.
