### ISSUE TITLE
Devirtualizeing question

### ISSUE THREAD

**Issue by smrbi** [wallds/NoVmpy#19]
Hi dear,

Please see this picture
![image](https://github.com/wallds/NoVmpy/assets/89096892/39b806b5-1625-4d87-af18-db7009ba4b6f)

what is mean or problem? "?UD"

**Comment by wallds** [comment]
https://github.com/wallds/NoVmpy/blob/d422dd2d09fc8cfc5e5df6d5dbf7650191205b87/novmpy/handler.py#L417-L423
